{% set name = "dust_extinction" %}
{% set version = "1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 54a119ec02cf4330c5f5d4053ed39e823f32d16d00d3c648ae9e4019611b9509
  patches:
    # See https://github.com/astropy/conda-channel-astropy/blob/d8148c76bc784febd6dc09a9322828bb82392cd7/requirements.yml#L22-L26
    # - 0001-Prevent-astropy_helpers-trying-to-auto-update.patch

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - setuptools_scm
    - astropy >=2
  run:
    - python >=3.5
    - numpy >=1.13
    - scipy
    - astropy >=2
    - matplotlib-base

test:
  imports:
    - dust_extinction

about:
  home: https://github.com/karllark/dust_extinction
  license: BSD 3-clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Models of interstellar dust extinction curves
  description: |
    Models of interstellar dust extinction curves using the
    astropy.modeling framework.  dust_extinction is an
    astropy affiliated package.
  doc_url: https://dust_extinction.readthedocs.io/
  dev_url: https://github.com/karllark/dust_extinction

extra:
  recipe-maintainers:
    - karllark
