{% set name = "dust_extinction" %}
{% set version = "0.8" %}
{% set hash_type = "sha256" %}
{% set hash_value = "f0e0fa0515f545f920f96b9f2fe5fabe299f1d8d297744421c256cf17915ae1a" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'
  patches:
    # See https://github.com/astropy/conda-channel-astropy/blob/d8148c76bc784febd6dc09a9322828bb82392cd7/requirements.yml#L22-L26
    - 0001-Prevent-astropy_helpers-trying-to-auto-update.patch

build:
  noarch: python
  number: 1
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - python >=3.5
    - pip
    - setuptools
    - astropy >=2
  run:
    - python >=3.5
    - numpy >=1.13
    - scipy
    - astropy >=2
    - matplotlib-base

test:
  imports:
    - dust_extinction

about:
  home: https://github.com/karllark/dust_extinction
  license: BSD 3-clause
  license_family: BSD
  license_file: licenses/LICENSE.rst
  summary: Models of interstellar dust extinction curves
  description: |
    Models of interstellar dust extinction curves using the
    astropy.modeling framework.  dust_extinction is an
    astropy affiliated package.
  doc_url: https://dust_extinction.readthedocs.io/
  dev_url: https://github.com/karllark/dust_extinction

extra:
  recipe-maintainers:
    - karllark
