travis:
  secure:
    BINSTAR_TOKEN: yZ0nTyqke/Wbo8jz/G48ZfzL4kLFLj43X4SZsab8TKtXUDLHB8dqrASU0XPdJSoxFEKLZlCqYUqZxta61pU9w3l2g0rBiIN5CEXeuhctgeamemktDhm/rMvRnAmps0ghTJu/uO/aZwX28QxLsH/pPfem4d2dWFUuZV5hr6ENIDPph+4HZOdqpL0YZK+YOmwBsmKJ+XXll1HcCgKUwlQrcaywshuPd8w8YDtGLu5DgBZSzHjz1i5EF4vObtLqw9hvCVOnDYYqPjzzhnbeY+C8mWPEDJ9xxk3pjUC14nWVBH7A6KXATTB6Aotr8XSqFk07jj9eKdamjTEtjMMZ0YlpuPho7drV9XVYZjOzaobwEtQJzf26d3DP8ZeQzdTJyhdpye8N6oZ6r8UmbAQWYqvRc78PXz6l0KicRdXcn2Wm/aoyNWc55r3owAQo2KHrv5eqcL532bu8WSoOTCzOGAw8x6RhEcMKoX1Dr1AZY7AatAJ0lMqOD2Sr85vzxztebKcDr8Gva5cg+u7DxPE3Iguxa/Nkjz5LDC7SGg0cyriC0U4ChyloLcQJWw8//y5TATr83wBAUGjhgHjr861e2zv0MZ27iOztNcd+cdBoKtKvl4WBOoD98uhkRy3CE5Bi4fzuczMC0vAb/tfjvM3+PAzSXCLAXedKji4RsHfXTkLsjLs=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
